//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.EntityModel
{
    using Data.EntityModel;
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUA
    {
        public string MASV { get; set; }
        public string MAMH { get; set; }
        public Nullable<double> DIEMSO { get; set; }
        public string XEPLOAI { get; set; }
    
        public virtual MONHOC MONHOC { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
